/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import Lectura.Archivo;
import Listas.Lista_Circular;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author jhonny
 */
public class Principal extends javax.swing.JFrame {
    private Archivo archi;
    private Ingreso_Jugador ij;
    private Lista_Circular jugador;
    private boolean isReadFile;
    //private Juego juego;
    //private Juego game;
    /**
     * Creates new form principal
     */
    public Principal() {
        archi = new Archivo();
        ij = new Ingreso_Jugador();
        jugador = new Lista_Circular();
        //juego = new Juego();
        //game = new Juego();
        initComponents();
        this.setTitle("Scrabble");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leer = new javax.swing.JButton();
        juga_r = new javax.swing.JButton();
        inicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leer.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        leer.setText("Leer Archivo");
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });

        juga_r.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        juga_r.setText("Ingresar Jugador");
        juga_r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juga_rActionPerformed(evt);
            }
        });

        inicio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        inicio.setText("Iniciar Juego");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(leer, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(juga_r))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juga_r, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
        // TODO add your handling code here:
        JFileChooser s = new JFileChooser();
        s.setDialogTitle("Selecccione un archivo");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos *.xml", "xml");
        s.setFileFilter(filter);
        //s.setCurrentDirectory(new File("C:/"));
        if(s.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            archi.leerXML(s.getSelectedFile().getPath());
            archi.getListaCasillaDobles().printList();
            System.out.println("");
            archi.getListaCasillasTriples().printList();
            System.out.println("");
            archi.getDiccionario().printList();
            isReadFile = true;
            JOptionPane.showMessageDialog(this, "Datos guardados", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_leerActionPerformed

    private void juga_rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juga_rActionPerformed
        // TODO add your handling code here:
        if(isReadFile){
            ij.setVisible(true);
            this.setVisible(false);
            ij.setP(this);
            ij.setJugador(getJugador());
        }else{
            JOptionPane.showMessageDialog(this, "Realice la lectura de un archivo\n antes de iniciar el juego", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_juga_rActionPerformed

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        Juego game = new Juego();
        game.setVisible(true);
        game.setP(this);
        if(ij.getJugador() != null){
            game.setJugador(this.ij.getJugador());
        }else{
            game.setJugador(jugador);
        }
        game.inicializarFichas();
        game.setDic(archi.getDiccionario());
        game.hiloDiccionario();
        game.hiloJugador();
        game.inicializarTurno();
        
        this.setVisible(false);
        
    }//GEN-LAST:event_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inicio;
    private javax.swing.JButton juga_r;
    private javax.swing.JButton leer;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jugador
     */
    public Lista_Circular getJugador() {
        return jugador;
    }

    /**
     * @param jugador the jugador to set
     */
    public void setJugador(Lista_Circular jugador) {
        this.jugador = jugador;
    }
}
